//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafariDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SafariDetail()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int SafariId { get; set; }
        public string SafariName { get; set; }
        public System.DateTime SafariDate { get; set; }
        public string SafariTime { get; set; }
        public int ParkId { get; set; }
        public decimal SafariCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Park Park { get; set; }
    }
}
