//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tourist
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MobileNo { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string EmailId { get; set; }
        public string IdentityName { get; set; }
        public string IdentityNumber { get; set; }
        public int BookingId { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
